### ISSUE TITLE
Missing from npm

### ISSUE THREAD

**Issue by chriszrc** [consbio/Leaflet.HtmlLegend#1]
This looks great! Tried to use it, but npm can't seem to find it :(

https://www.npmjs.com/search?q=leaflet+html+legend

Also, after adding this package directly from github, it seems the package.json is missing a main entry:

`"main": "L.Control.HtmlLegend.min.js"`

I'm not an npm expert, but this made things work-

**Comment by chriszrc** [comment]
Any update here? Or is there a better way to import the script directly?

**Comment by ka7eh** [comment]
@chriszrc I'll try to make the package ready for a release soon (hopefully this week) and push it to npmjs.

**Comment by ka7eh** [comment]
@chriszrc I released the package on `npmjs` and it should be installable from it now.
