### ISSUE TITLE
Legend to collapse by default

### ISSUE THREAD

**Issue by minhtam-nguyennhat** [consbio/Leaflet.HtmlLegend#3]
Hi,

First of all, thanks for this plugin, it is awesome :+1: 

Just wondering is there a way to have the legend to collapse by default instead of all being expanded?

Thanks,
Tam

**Comment by ka7eh** [comment]
I think the best solution is allowing users to set the default behavior they need in options.
I'll make the changes soon.

**Comment by ka7eh** [comment]
Fixed here: https://github.com/consbio/Leaflet.HtmlLegend/commit/b0fd45373fbaace21e8cd83a9326cef7691eb8a3
Now you can set `collapsedOnInit` to `true` to initialize your legend in collapsed mode.
