### ISSUE TITLE
Caption from a layer

### ISSUE THREAD

**Issue by HerminioSabino** [consbio/Leaflet.HtmlLegend#8]
Good Morning,
I would like to know if you can use a one-layer style to be part of the caption.
EX: I have a layer with the regions division of a particular state, and I would like the caption was the style that I preset.

How can I do this?:

Thanks in advance

**Comment by ka7eh** [comment]
@HerminioSabino you should be able to customize the header for each section using css. For sub-items of each layer, you can define their styling when initializing the control.

Check out the examples to see how you can configure the legend control:
https://consbio.github.io/Leaflet.HtmlLegend/
https://github.com/consbio/Leaflet.HtmlLegend/blob/master/index.html

If none of the examples work for you, please post a sketch of what you are trying to achieve so I can point you to the relevant config.

**Comment by HerminioSabino** [comment]
First of all, thank you very much for the feedback,

Here is the example I need,
I can already separate my layers for groups, but in the image I am sending is an example with only one layer.
I want the layer control to contain only the name, and the symbology is as in the examples you sent. In my case I want to take advantage of the symbology that is already defined in the layer.
As I use the Qgis plugin (QGIS2web), it already returns the code (attached). where symbology is defined by
**function style_24MEE250GC_SIR_0_0**.
I want, if possible, to use this style wherever you put it.

**style: {



                     'background-color': 'green',
                     'width': '10px',
                     'height': '10px'**
I am attaching two images and also the folder with the small example.

I do not know if I explained it well, but I would like a lot of help, since it is an important step for my graduation.

![img2](https://user-images.githubusercontent.com/27819904/50493882-55150300-0a07-11e9-8f5f-4e479df8220e.jpg)
![img 1](https://user-images.githubusercontent.com/27819904/50493883-55150300-0a07-11e9-94b3-8d1ffa674cd2.jpg)

[QGIS.zip](https://github.com/consbio/Leaflet.HtmlLegend/files/2713329/QGIS.zip)
